name: PR Source Code Check

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run ESLint
        run: yarn lint

  tsc:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run type check
        run: yarn tsc

  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install packages
        run: yarn
      - name: Run prettier
        run: yarn format
